# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justin Murphy-Mancini
email: jmm@justinmurphymancini.com
description: > # this means to ignore newlines until "baseurl:"
  Justin Murphy-Mancini is a composer and keyboardist performing as a
  historical, contemporary, and liturgical musician.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://justinmurphymancini.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
